name: Acunetix workflow

on:
    push:
      branches: [main]
      
jobs:

    netspaker_scan_job:
        runs-on: ubuntu-20.04
        steps:
          # Starts actions with given inputs
          - name: Start Netsparker Enterprise Scan
            uses: netsparker/Netsparker-Cloud-GitHub-Actions@v0.0.1
            id: netsparker-enterprise-scan-step
            with:
              website-id: '4fdb7266-fdac-4dec-a190-aeac02e81366'
              scan-type: 'Incremental'
              profile-id: '14796d6d-4560-4bec-945a-aed701a0857a'
              user-id: ${{ secrets.NETSPARKER_USER_ID }}
              api-token: ${{ secrets.NETSPARKER_API_TOKEN }}
              base-url: 'https://www.netsparkercloud.com'
          # Displays output for action
          - name: Display Scan Request Message
            run: echo "${{ steps.netsparker-enterprise-scan-step.outputs.scan-message }}"
